name: Check bash style

# Check this on the 1st day of the month.
# 1st as the first letter of this repo is the 1st letter in the alphabet.
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"


jobs:
  check_bash_style:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Check bash scripts for style
        run: shellcheck scripts/*.sh
